@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxOTY5MzcxOC04MGE4LTRjYzctODkwYi1hNWRjNTY4NjU0NjEiLCJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzczNDI3OTMyLCJleHAiOjE3NzM0MzE1MzIsImlhdCI6MTc3MzQyNzkzMiwiaXNzIjoiR2VuaXVzT3JkZXJzLkFwaSIsImF1ZCI6Ikdlbml1c09yZGVycy5DbGllbnQifQ.iREo_MkBcgg3X8YYiwcppARqBGAULLAsX3cS9WODFc0
POST http://localhost:5289/api/decision/create
Authorization: Bearer {{token}}
Content-Type:application/json

{
    "DecisionNumber":2,
    "DecisionYear": 2026,
    "DecisionDate": "2026-01-01",
    "Content":"قرار نقل السيد لوظفية",
    "Attachment": null
}

###
GET  http://localhost:5289/api/decision/1
Authorization: Bearer {{token}}

###
DELETE   http://localhost:5289/api/decision/delete/1

###
GET  http://localhost:5289/api/decision
Authorization: Bearer {{token}}
###
Put  http://localhost:5289/api/decision/update/4
Content-Type: application/json

{
    "decisionNumber": 14,
    "decisionYear": 2025,
    "decisionDate": "2025-01-01",
    "content": "قرار تعيين السيد لوظفية",
    "attachment": "يلبيللي"
}
###
POST http://localhost:5289/api/account/register
Authorization: Bearer {{token}}
Content-Type:application/json

{
    "fullName": "shaban",
    "username": "shaban",
    "department": "IT",
    "password": "Password123!"
}


####
POST http://localhost:5289/api/account/login
Content-Type:application/json

{
    "username": "Admin",
    "password": "Admin@123"
}